version: 1.0.{build}
image: Visual Studio 2015
environment: 
  access_token:
    secure: Xu3+xPTTII2UDM8Bc6DH0H82IlTLOdJ3+ROJBOP84PvWvuYotiNk/OHRw+eMVuur
build_script: 
- ps: 
    .\build.ps1 
artifacts: 
- path: docs 
  name: out
on_success: 
- ps: |
    & git config --global credential.helper store
    Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    & git config --global user.email "Appveyor Deploy" 
    & git config --global user.name "Appveyor Deploy"
    $repourl = & git config --get remote.origin.url
    & git clone $repourl pages 
    cd pages 
    & git checkout gh-pages
    & git status
    Remove-Item -recurse docs 
    Move-Item ..\docs . 
    & git status
    & git add -A
    & git commit '--allow-empty' '-m' "pages commit $VERSION" 
    & git status
    & git push origin gh-pages
